version: "2"
services:
  pkg_sender:
    build: .
    container_name: pkg_sender
    volumes:
      - /srv/mergerfs/pool/data/downloads/PS4_Games:/opt/apps/pkg_sender/files
    ports:
      - 3333:8080
    environment:
      - PORT=8080
      - STATIC_FILES=/opt/apps/pkg_sender/files
      - LOCALIP=192.168.1.6
      - PS4IP=192.168.1.9
    restart: unless-stopped
